[tool.poetry]
name = "staircase"
version = "0.1.0"
description = "Modelling of quantitative state changes as step functions"
authors = ["Riley Clement <venaturum@gmail.com>"]
maintainers = ["Riley Clement <venaturum@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://stairs.readthedocs.io/en/latest/"
repository = "https://github.com/venaturum/staircase"
documentation = "https://stairs.readthedocs.io/en/latest/"
keywords = ["Staircase",
			"Step Functions",
			"Data Analysis",
			"Intervals",
			"Simulation"]

[tool.poetry.dependencies]
python = "^3.6"
sortedcontainers = "^2.1"
pandas = "*"
numpy = "*"


[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
